- newPredictor:
    call: http.get
    args:
        url: https://helloworld-s3yk5iivva-uc.a.run.app/newspredict
        auth:
            type: OIDC
- maPredictor:
    call: http.get
    args:
        url: https://helloworld-s3yk5iivva-uc.a.run.app/mapredict
        auth:
            type: OIDC  
- BQuery:
    call: http.post
    args:
        url: https://helloworld-s3yk5iivva-uc.a.run.app/buuperday
        body:
            query: SELECT * FROM `iwasnothing-self-learning.stock_cor.ma_predict_short_list` 
        auth:
            type: OIDC  